In [1]:
# !pip install googletrans==3.1.0a0
# !pip install google_trans_new
# !pip install googletrans==3.1.0a0

In [2]:
import pandas as pd
import re
import unicodedata
import matplotlib.pyplot as plt
import tqdm
import japanize_matplotlib
import os
import collections
import glob
import math
from googletrans import Translator

In [3]:
f_scientist = pd.read_csv("f_scientist_text_overall.csv")
m_scientist = pd.read_csv("m_scientist_text_overall.csv")

In [4]:
f_scientist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21815 entries, 0 to 21814
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   word      21815 non-null  object
 1   pos       21815 non-null  object
 2   total     21815 non-null  int64
 3   articles  21815 non-null  int64
dtypes: int64(2), object(2)
memory usage: 681.8+ KB

In [5]:
m_scientist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62454 entries, 0 to 62453
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   word      62454 non-null  object
 1   pos       62454 non-null  object
 2   total     62454 non-null  int64
 3   articles  62454 non-null  int64
dtypes: int64(2), object(2)
memory usage: 1.9+ MB

In [6]:
f_scientist.pos.unique()

array(['名詞', '動詞', '形容詞'], dtype=object)

- 名詞 = noun
- 動詞 = verb
- 形容詞 = adjective

In [7]:
f_scientist[f_scientist.pos == "形容詞"].head()

    word  pos  total  articles
34    ない  形容詞    586       218
238   強い  形容詞    166       108
251   多い  形容詞    158        93
271   高い  形容詞    147        97
278  新しい  形容詞    142        90

### Number of total articles of each category

In [8]:
# CHANGE DIRECTORY PATH!!!
f_scientist_total_articles = len(glob.glob('../f_scientist/new_csvs/*'))
f_scientist_total_articles

6439

In [9]:
# CHANGE DIRECTORY PATH!!!
m_scientist_total_articles = len(glob.glob('../m_scientist/new_csvs/*'))
m_scientist_total_articles

24561

In [36]:
# all nouns
f_scientist_noun= f_scientist[f_scientist.pos =="名詞"].sort_values("total", ascending=False)
f_scientist_noun["per_article"]= round(f_scientist_noun["articles"]/ f_scientist_total_articles,2)
f_scientist_noun["gender"]= "female"
f_scientist_noun["occupation"]= "scientist"
f_scientist_noun.to_csv("f_scientist_noun.csv", index= False)
print_result = pd.read_csv("f_scientist_noun.csv")
print_result.head()

  word pos  total  articles  per_article  gender occupation
0   研究  名詞   4261       966         0.15  female  scientist
1   大学  名詞   2918       849         0.13  female  scientist
2    学  名詞   2900       878         0.14  female  scientist
3   教授  名詞   2275       867         0.13  female  scientist
4   日本  名詞   2220       804         0.12  female  scientist

In [37]:
# top 20 nouns
f_scientist_top20_noun= f_scientist_noun.head(20)
f_scientist_top20_noun.to_csv("f_scientist_top20_noun.csv", index= False)
print_result = pd.read_csv("f_scientist_top20_noun.csv")
print_result.head()

  word pos  total  articles  per_article  gender occupation
0   研究  名詞   4261       966         0.15  female  scientist
1   大学  名詞   2918       849         0.13  female  scientist
2    学  名詞   2900       878         0.14  female  scientist
3   教授  名詞   2275       867         0.13  female  scientist
4   日本  名詞   2220       804         0.12  female  scientist

In [38]:
# all verbs

f_scientist_verb= f_scientist[f_scientist.pos =="動詞"].sort_values("total", ascending=False)
f_scientist_verb["per_article"]= round(f_scientist_verb["articles"]/ f_scientist_total_articles,2)
f_scientist_verb["gender"]= "female"
f_scientist_verb["occupation"]= "scientist"
f_scientist_verb.to_csv("f_scientist_verb.csv", index= False)
print_result = pd.read_csv("f_scientist_verb.csv")
print_result.head()

   word pos  total  articles  per_article  gender occupation
0    行う  動詞    910       401         0.06  female  scientist
1   受ける  動詞    757       316         0.05  female  scientist
2   務める  動詞    748       420         0.07  female  scientist
3   できる  動詞    634       216         0.03  female  scientist
4  生まれる  動詞    547       439         0.07  female  scientist

In [13]:
# TOP 20 verbs
f_scientist_top20_verb= f_scientist_verb.head(20)
f_scientist_top20_verb.to_csv("f_scientist_top20_verb.csv", index= False)
print_result = pd.read_csv("f_scientist_top20_verb.csv")
print_result.head()

   word pos  total  articles  per_article
0    行う  動詞    910       401         0.06
1   受ける  動詞    757       316         0.05
2   務める  動詞    748       420         0.07
3   できる  動詞    634       216         0.03
4  生まれる  動詞    547       439         0.07

In [39]:
# all adj
f_scientist_adj= f_scientist[f_scientist.pos =="形容詞"].sort_values("total", ascending=False)
f_scientist_adj["per_article"]= round(f_scientist_adj["articles"]/ f_scientist_total_articles,2)
f_scientist_adj["gender"]= "female"
f_scientist_adj["occupation"]= "scientist"
f_scientist_adj.to_csv("f_scientist_adj.csv", index= False)
print_result = pd.read_csv("f_scientist_adj.csv")
print_result.head()

  word  pos  total  articles  per_article  gender occupation
0   ない  形容詞    586       218         0.03  female  scientist
1   強い  形容詞    166       108         0.02  female  scientist
2   多い  形容詞    158        93         0.01  female  scientist
3   高い  形容詞    147        97         0.02  female  scientist
4  新しい  形容詞    142        90         0.01  female  scientist

In [40]:
# top 20 adj
f_scientist_top20_adj= f_scientist_adj.head(20)
f_scientist_top20_adj.to_csv("f_scientist_top20_adj.csv", index= False)
print_result = pd.read_csv("f_scientist_top20_adj.csv")
print_result.head()

  word  pos  total  articles  per_article  gender occupation
0   ない  形容詞    586       218         0.03  female  scientist
1   強い  形容詞    166       108         0.02  female  scientist
2   多い  形容詞    158        93         0.01  female  scientist
3   高い  形容詞    147        97         0.02  female  scientist
4  新しい  形容詞    142        90         0.01  female  scientist

In [41]:
# merge noun+ verb+ adj analysis
f_scientist_top_words = pd.concat([f_scientist_noun, f_scientist_verb,f_scientist_adj], axis=0)
f_scientist_top_words.to_csv("f_scientist_top_words.csv", index= False)
print_result = pd.read_csv("f_scientist_top_words.csv")
print_result

          word  pos  total  articles  per_article  gender occupation
0           研究   名詞   4261       966         0.15  female  scientist
1           大学   名詞   2918       849         0.13  female  scientist
2            学   名詞   2900       878         0.14  female  scientist
3           教授   名詞   2275       867         0.13  female  scientist
4           日本   名詞   2220       804         0.12  female  scientist
...        ...  ...    ...       ...          ...     ...        ...
21810      にがい  形容詞      1         1         0.00  female  scientist
21811   にぎにぎしい  形容詞      1         1         0.00  female  scientist
21812     にげない  形容詞      1         1         0.00  female  scientist
21813  言うまでもない  形容詞      1         1         0.00  female  scientist
21814     歯がゆい  形容詞      1         1         0.00  female  scientist

[21815 rows x 7 columns]

## Male scientists

In [45]:
#total number of articles
m_scientist_total_articles = len(glob.glob('../m_scientist/new_csvs/*'))

# all nouns
m_scientist_noun= m_scientist[m_scientist.pos =="名詞"].sort_values("total", ascending=False)
m_scientist_noun["per_article"]= round(m_scientist_noun["articles"]/ m_scientist_total_articles,2)
m_scientist_noun["gender"]= "male"
m_scientist_noun["occupation"]= "scientist"
m_scientist_noun.to_csv("m_scientist_noun.csv", index= False)
# print_result = pd.read_csv("m_scientist_noun.csv")

# top20 nouns
m_scientist_top20_noun= m_scientist_noun.head(20)
m_scientist_top20_noun.to_csv("m_scientist_top20_noun.csv", index= False)
# print_result = pd.read_csv("m_scientist_top20_noun.csv")

# all verbs
m_scientist_verb= m_scientist[m_scientist.pos =="動詞"].sort_values("total", ascending=False)
m_scientist_verb["per_article"]= round(m_scientist_verb["articles"]/ m_scientist_total_articles,2)
m_scientist_verb["gender"]= "male"
m_scientist_verb["occupation"]= "scientist"
m_scientist_verb.to_csv("m_scientist_verb.csv", index= False)
# print_result = pd.read_csv("m_scientist_verb.csv")

# top20 verbs
m_scientist_top20_verb= m_scientist_verb.head(20)
m_scientist_top20_verb.to_csv("m_scientist_top20_verb.csv", index= False)
# print_result = pd.read_csv("m_scientist_top20_verb.csv")

# all adjs
m_scientist_adj= m_scientist[m_scientist.pos =="形容詞"].sort_values("total", ascending=False)
m_scientist_adj["per_article"]= round(m_scientist_adj["articles"]/ m_scientist_total_articles,2)
m_scientist_adj["gender"]= "male"
m_scientist_adj["occupation"]= "scientist"
m_scientist_adj.to_csv("m_scientist_adj.csv", index= False)
# print_result = pd.read_csv("m_scientist_adj.csv")

# top20 adj
m_scientist_top20_adj= m_scientist_adj.head(20)
m_scientist_top20_adj.to_csv("m_scientist_top20_adj.csv", index= False)

In [46]:
# merge nouns + verbs + adjs
m_scientist_top_words = pd.concat([m_scientist_noun, m_scientist_verb,m_scientist_adj], axis=0)
m_scientist_top_words.to_csv("m_scientist_top_words.csv", index= False)
print_result = pd.read_csv("m_scientist_top_words.csv")
print_result

         word  pos  total  articles  per_article gender occupation
0          研究   名詞  62473     17011         0.69   male  scientist
1          教授   名詞  49488     18099         0.74   male  scientist
2           学   名詞  46580     14842         0.60   male  scientist
3          大学   名詞  45604     15050         0.61   male  scientist
4          日本   名詞  40098     16587         0.68   male  scientist
...       ...  ...    ...       ...          ...    ...        ...
62449   おそろしい  形容詞      1         1         0.00   male  scientist
62450  おぼつかない  形容詞      1         1         0.00   male  scientist
62451  いかがわしい  形容詞      1         1         0.00   male  scientist
62452   ふがいない  形容詞      1         1         0.00   male  scientist
62453    湿っぽい  形容詞      1         1         0.00   male  scientist

[62454 rows x 7 columns]

In [47]:
# f+m scientist 
scientist_all_top_words = pd.concat([f_scientist_top_words, m_scientist_top_words], axis=0)
scientist_all_top_words.to_csv("scientist_all_top_words.csv", index= False)

In [48]:
scientist_all_top_words= pd.read_csv("scientist_all_top_words.csv")
scientist_all_top_words

         word  pos  total  articles  per_article  gender occupation
0          研究   名詞   4261       966         0.15  female  scientist
1          大学   名詞   2918       849         0.13  female  scientist
2           学   名詞   2900       878         0.14  female  scientist
3          教授   名詞   2275       867         0.13  female  scientist
4          日本   名詞   2220       804         0.12  female  scientist
...       ...  ...    ...       ...          ...     ...        ...
84264   おそろしい  形容詞      1         1         0.00    male  scientist
84265  おぼつかない  形容詞      1         1         0.00    male  scientist
84266  いかがわしい  形容詞      1         1         0.00    male  scientist
84267   ふがいない  形容詞      1         1         0.00    male  scientist
84268    湿っぽい  形容詞      1         1         0.00    male  scientist

[84269 rows x 7 columns]

In [61]:
scientist_all_top_words[scientist_all_top_words.word == "瞳"]

      word pos  total  articles  per_article  gender occupation
6631     瞳  名詞      4         3          0.0  female  scientist
46085    瞳  名詞      6         5          0.0    male  scientist

In [196]:
# difference??
diff_sci = pd.merge(f_scientist_top_words, m_scientist_top_words, on="word")
diff_sci["diff_pct"] = abs(diff_sci.per_article_x - diff_sci.per_article_y)
diff_sci["diff_pct"].describe()

count    20583.000000
mean         0.002855
std          0.014834
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.610000
Name: diff_pct, dtype: float64

In [203]:
diff_sci.sort_values("diff_pct", ascending = False).head(10)

,word,pos_x,total_x,articles_x,per_article_x,gender_x,occupation_x,pos_y,total_y,articles_y,per_article_y,gender_y,occupation_y,diff_pct
3,教授,名詞,2275,867,0.13,female,scientist,名詞,49488,18099,0.74,male,scientist,0.61
4,日本,名詞,2220,804,0.12,female,scientist,名詞,40098,16587,0.68,male,scientist,0.56
0,研究,名詞,4261,966,0.15,female,scientist,名詞,62473,17011,0.69,male,scientist,0.54
1,大学,名詞,2918,849,0.13,female,scientist,名詞,45604,15050,0.61,male,scientist,0.48
2,学,名詞,2900,878,0.14,female,scientist,名詞,46580,14842,0.60,male,scientist,0.46
9,学者,名詞,1318,833,0.13,female,scientist,名詞,20988,14110,0.57,male,scientist,0.44
8,博士,名詞,1356,751,0.12,female,scientist,名詞,20821,12783,0.52,male,scientist,0.40
13,卒業,名詞,961,673,0.10,female,scientist,名詞,14050,10805,0.44,male,scientist,0.34
38,名誉,名詞,519,325,0.05,female,scientist,名詞,13654,8223,0.33,male,scientist,0.28
23,専門,名詞,687,549,0.09,female,scientist,名詞,11069,8797,0.36,male,scientist,0.27

## Japanese Female Idols vs Male Idols

In [63]:
# read overall file
japaneseFemaleIdol = pd.read_csv("japeseFemaleIdol_text_overall.csv")

#total number of articles
japaneseFemaleIdol_total_articles = len(glob.glob('../japaneseFemaleIdol/new_csvs/*'))

# all nouns
japaneseFemaleIdol_noun= japaneseFemaleIdol[japaneseFemaleIdol.pos =="名詞"].sort_values("total", ascending=False)
japaneseFemaleIdol_noun["per_article"]= round(japaneseFemaleIdol_noun["articles"]/ japaneseFemaleIdol_total_articles,2)
japaneseFemaleIdol_noun["gender"]= "female"
japaneseFemaleIdol_noun["occupation"]= "Japanese idol"
japaneseFemaleIdol_noun.to_csv("japaneseFemaleIdol_noun.csv", index= False)
# print_result = pd.read_csv("japaneseFemaleIdol_noun.csv")

# top20 nouns
japaneseFemaleIdol_top20_noun= japaneseFemaleIdol_noun.head(20)
japaneseFemaleIdol_top20_noun.to_csv("japaneseFemaleIdol_top20_noun.csv", index= False)
# print_result = pd.read_csv("japaneseFemaleIdol_top20_noun.csv")

# all verbs
japaneseFemaleIdol_verb= japaneseFemaleIdol[japaneseFemaleIdol.pos =="動詞"].sort_values("total", ascending=False)
japaneseFemaleIdol_verb["per_article"]= round(japaneseFemaleIdol_verb["articles"]/ japaneseFemaleIdol_total_articles,2)
japaneseFemaleIdol_verb["gender"]= "female"
japaneseFemaleIdol_verb["occupation"]= "Japanese idol"
japaneseFemaleIdol_verb.to_csv("japaneseFemaleIdol_verb.csv", index= False)
# print_result = pd.read_csv("japaneseFemaleIdol_verb.csv")

# top20 verbs
japaneseFemaleIdol_top20_verb= japaneseFemaleIdol_verb.head(20)
japaneseFemaleIdol_top20_verb.to_csv("japaneseFemaleIdol_top20_verb.csv", index= False)
# print_result = pd.read_csv("japaneseFemaleIdol_top20_verb.csv")

# all adjs
japaneseFemaleIdol_adj= japaneseFemaleIdol[japaneseFemaleIdol.pos =="形容詞"].sort_values("total", ascending=False)
japaneseFemaleIdol_adj["per_article"]= round(japaneseFemaleIdol_adj["articles"]/ japaneseFemaleIdol_total_articles,2)
japaneseFemaleIdol_adj["gender"]= "female"
japaneseFemaleIdol_adj["occupation"]= "Japanese idol"
japaneseFemaleIdol_adj.to_csv("japaneseFemaleIdol_adj.csv", index= False)
# print_result = pd.read_csv("japaneseFemaleIdol_adj.csv")

# top20 adj
japaneseFemaleIdol_top20_adj= japaneseFemaleIdol_adj.head(20)
japaneseFemaleIdol_top20_adj.to_csv("japaneseFemaleIdol_top20_adj.csv", index= False)

In [64]:
# merge nouns + verbs + adjs
japaneseFemaleIdol_top_words = pd.concat([japaneseFemaleIdol_noun, japaneseFemaleIdol_verb,japaneseFemaleIdol_adj], axis=0)
japaneseFemaleIdol_top_words.to_csv("japaneseFemaleIdol_top_words.csv", index= False)
print_result = pd.read_csv("japaneseFemaleIdol_top_words.csv")
print_result

         word  pos  total  articles  per_article  gender     occupation
0        アイドル   名詞  15624      3716         0.73  female  Japanese idol
1          活動   名詞  12470      2334         0.46  female  Japanese idol
2          所属   名詞  10798      3322         0.65  female  Japanese idol
3          出演   名詞  10362      1838         0.36  female  Japanese idol
4          日本   名詞  10072      3966         0.78  female  Japanese idol
...       ...  ...    ...       ...          ...     ...            ...
27572     とろい  形容詞      2         1         0.00  female  Japanese idol
27573  なまめかしい  形容詞      2         1         0.00  female  Japanese idol
27574   つまんない  形容詞      2         1         0.00  female  Japanese idol
27575     つよい  形容詞      2         1         0.00  female  Japanese idol
27576     宜しい  形容詞      2         1         0.00  female  Japanese idol

[27577 rows x 7 columns]

In [67]:
# read overall file
japaneseMaleIdol = pd.read_csv("japeseMaleIdol_text_overall.csv")

#total number of articles
japaneseMaleIdol_total_articles = len(glob.glob('../japaneseMaleIdol/new_csvs/*'))

# all nouns
japaneseMaleIdol_noun= japaneseMaleIdol[japaneseMaleIdol.pos =="名詞"].sort_values("total", ascending=False)
japaneseMaleIdol_noun["per_article"]= round(japaneseMaleIdol_noun["articles"]/ japaneseMaleIdol_total_articles,2)
japaneseMaleIdol_noun["gender"]= "male"
japaneseMaleIdol_noun["occupation"]= "Japanese idol"
japaneseMaleIdol_noun.to_csv("japaneseMaleIdol_noun.csv", index= False)
# print_result = pd.read_csv("japaneseMaleIdol_noun.csv")

# top20 nouns
japaneseMaleIdol_top20_noun= japaneseMaleIdol_noun.head(20)
japaneseMaleIdol_top20_noun.to_csv("japaneseMaleIdol_top20_noun.csv", index= False)
# print_result = pd.read_csv("japaneseMaleIdol_top20_noun.csv")

# all verbs
japaneseMaleIdol_verb= japaneseMaleIdol[japaneseMaleIdol.pos =="動詞"].sort_values("total", ascending=False)
japaneseMaleIdol_verb["per_article"]= round(japaneseMaleIdol_verb["articles"]/ japaneseMaleIdol_total_articles,2)
japaneseMaleIdol_verb["gender"]= "male"
japaneseMaleIdol_verb["occupation"]= "Japanese idol"
japaneseMaleIdol_verb.to_csv("japaneseMaleIdol_verb.csv", index= False)
# print_result = pd.read_csv("japaneseMaleIdol_verb.csv")

# top20 verbs
japaneseMaleIdol_top20_verb= japaneseMaleIdol_verb.head(20)
japaneseMaleIdol_top20_verb.to_csv("japaneseMaleIdol_top20_verb.csv", index= False)
# print_result = pd.read_csv("japaneseMaleIdol_top20_verb.csv")

# all adjs
japaneseMaleIdol_adj= japaneseMaleIdol[japaneseMaleIdol.pos =="形容詞"].sort_values("total", ascending=False)
japaneseMaleIdol_adj["per_article"]= round(japaneseMaleIdol_adj["articles"]/ japaneseMaleIdol_total_articles,2)
japaneseMaleIdol_adj["gender"]= "male"
japaneseMaleIdol_adj["occupation"]= "Japanese idol"
japaneseMaleIdol_adj.to_csv("japaneseMaleIdol_adj.csv", index= False)
# print_result = pd.read_csv("japaneseMaleIdol_adj.csv")

# top20 adj
japaneseMaleIdol_top20_adj= japaneseMaleIdol_adj.head(20)
japaneseMaleIdol_top20_adj.to_csv("japaneseMaleIdol_top20_adj.csv", index= False)

In [68]:
# merge nouns + verbs + adjs
japaneseMaleIdol_top_words = pd.concat([japaneseMaleIdol_noun, japaneseMaleIdol_verb,japaneseMaleIdol_adj], axis=0)
japaneseMaleIdol_top_words.to_csv("japaneseMaleIdol_top_words.csv", index= False)
print_result = pd.read_csv("japaneseMaleIdol_top_words.csv")
print_result

       word  pos  total  articles  per_article gender     occupation
0        出演   名詞    506       109         0.57   male  Japanese idol
1        日本   名詞    408       161         0.84   male  Japanese idol
2        番組   名詞    382        87         0.45   male  Japanese idol
3        活動   名詞    357       105         0.55   male  Japanese idol
4         草   名詞    344         5         0.03   male  Japanese idol
...     ...  ...    ...       ...          ...    ...            ...
9881  あったかい  形容詞      1         1         0.01   male  Japanese idol
9882    あさい  形容詞      1         1         0.01   male  Japanese idol
9883   うれしい  形容詞      1         1         0.01   male  Japanese idol
9884    うとい  形容詞      1         1         0.01   male  Japanese idol
9885    根強い  形容詞      1         1         0.01   male  Japanese idol

[9886 rows x 7 columns]

In [69]:
# f+m idol
japaneseIdol_all_top_words = pd.concat([japaneseFemaleIdol_top_words, japaneseMaleIdol_top_words], axis=0)
japaneseIdol_all_top_words.to_csv("japaneseIdol_all_top_words.csv", index= False)

In [94]:
japaneseIdol_all_top_words= pd.read_csv("japaneseIdol_all_top_words.csv")
japaneseIdol_all_top_words[japaneseIdol_all_top_words.word == "スキャンダル"]

        word pos  total  articles  per_article  gender     occupation
4645  スキャンダル  名詞     26        13          0.0  female  Japanese idol

In [90]:
japaneseIdol_all_top_words[japaneseIdol_all_top_words.gender == "male"]\
    .sort_values("per_article", ascending = False).head(60)

          word  pos  total  articles  per_article gender     occupation
27578       日本   名詞    408       161         0.84   male  Japanese idol
27598       出身   名詞    184       152         0.79   male  Japanese idol
27587       所属   名詞    268       146         0.76   male  Japanese idol
27586     アイドル   名詞    289       118         0.61   male  Japanese idol
27582     メンバー   名詞    326       117         0.61   male  Japanese idol
27590       俳優   名詞    241       116         0.60   male  Japanese idol
27577       出演   名詞    506       109         0.57   male  Japanese idol
27580       活動   名詞    357       105         0.55   male  Japanese idol
27584      事務所   名詞    314        97         0.51   male  Japanese idol
27592     グループ   名詞    227        98         0.51   male  Japanese idol
27583     デビュー   名詞    315        97         0.51   male  Japanese idol
27593       歌手   名詞    212        90         0.47   male  Japanese idol
27579       番組   名詞    382        87         0.45   male  Japanese idol
27612       男性   名詞    127        84         0.44   male  Japanese idol
27601       東京   名詞    167        76         0.40   male  Japanese idol
27613     タレント   名詞    124        76         0.40   male  Japanese idol
36037      務める   動詞    145        69         0.36   male  Japanese idol
27631       人物   名詞     88        69         0.36   male  Japanese idol
27622       卒業   名詞    103        70         0.36   male  Japanese idol
27597      テレビ   名詞    197        69         0.36   male  Japanese idol
27616       結成   名詞    119        70         0.36   male  Japanese idol
27660       来歴   名詞     68        68         0.35   male  Japanese idol
27618  オーディション   名詞    112        66         0.34   male  Japanese idol
27608       芸能   名詞    137        63         0.33   male  Japanese idol
27632       学校   名詞     88        64         0.33   male  Japanese idol
27588      ニーズ   名詞    251        62         0.32   male  Japanese idol
27599       同年   名詞    184        62         0.32   male  Japanese idol
27589       ジャ   名詞    250        61         0.32   male  Japanese idol
27585       映画   名詞    310        59         0.31   male  Japanese idol
27667       愛称   名詞     64        60         0.31   male  Japanese idol
36036       行う   動詞    157        57         0.30   male  Japanese idol
27621       参加   名詞    104        56         0.29   male  Japanese idol
27602        位   名詞    167        56         0.29   male  Japanese idol
27614       発表   名詞    124        53         0.28   male  Japanese idol
27659       高等   名詞     68        54         0.28   male  Japanese idol
27605       音楽   名詞    158        53         0.28   male  Japanese idol
27600       当時   名詞    178        54         0.28   male  Japanese idol
27594      ドラマ   名詞    211        54         0.28   male  Japanese idol
27615     シングル   名詞    121        53         0.28   male  Japanese idol
27624        型   名詞    100        51         0.27   male  Japanese idol
27596        曲   名詞    200        51         0.27   male  Japanese idol
37286       ない  形容詞    128        50         0.26   male  Japanese idol
27606       自身   名詞    147        49         0.26   male  Japanese idol
27610       時代   名詞    129        50         0.26   male  Japanese idol
27591       主演   名詞    227        50         0.26   male  Japanese idol
36041      受ける   動詞     99        48         0.25   male  Japanese idol
27712       血液   名詞     48        48         0.25   male  Japanese idol
27685       本名   名詞     57        46         0.24   male  Japanese idol
27620       舞台   名詞    112        47         0.24   male  Japanese idol
27604       放送   名詞    163        44         0.23   male  Japanese idol
27639       高校   名詞     80        45         0.23   male  Japanese idol
27670       誕生   名詞     63        43         0.22   male  Japanese idol
27648       現在   名詞     73        42         0.22   male  Japanese idol
27609       作品   名詞    133        43         0.22   male  Japanese idol
27619      ダンス   名詞    112        43         0.22   male  Japanese idol
27743       身長   名詞     41        40         0.21   male  Japanese idol
27635     レコード   名詞     87        40         0.21   male  Japanese idol
36039       いう   動詞    112        40         0.21   male  Japanese idol
36040       言う   動詞    104        41         0.21   male  Japanese idol
27623      ライブ   名詞    100        40         0.21   male  Japanese idol

In [191]:
# difference??
diff_idol = pd.merge(japaneseFemaleIdol_top_words, japaneseMaleIdol_top_words, on="word")
diff_idol["diff_pct"] = abs(diff_idol.per_article_x - diff_idol.per_article_y)
diff_idol["diff_pct"].describe()

count    8459.000000
mean        0.015547
std         0.020124
min         0.000000
25%         0.010000
50%         0.010000
75%         0.020000
max         0.570000
Name: diff_pct, dtype: float64

In [205]:
diff_idol.sort_values("diff_pct", ascending = False).head(20)

,word,pos_x,total_x,articles_x,per_article_x,gender_x,occupation_x,pos_y,total_y,articles_y,per_article_y,gender_y,occupation_y,diff_pct
296,俳優,名詞,484,170,0.03,female,Japanese idol,名詞,241,116,0.60,male,Japanese idol,0.57
228,男性,名詞,582,240,0.05,female,Japanese idol,名詞,127,84,0.44,male,Japanese idol,0.39
9,グラビア,名詞,6646,1987,0.39,female,Japanese idol,名詞,3,2,0.01,male,Japanese idol,0.38
2920,ジャ,名詞,34,15,0.00,female,Japanese idol,名詞,250,61,0.32,male,Japanese idol,0.32
4146,ニーズ,名詞,16,6,0.00,female,Japanese idol,名詞,251,62,0.32,male,Japanese idol,0.32
22,歌手,名詞,4232,1026,0.20,female,Japanese idol,名詞,212,90,0.47,male,Japanese idol,0.27
10,女優,名詞,5948,1716,0.34,female,Japanese idol,名詞,27,16,0.08,male,Japanese idol,0.26
24,事務所,名詞,4114,1278,0.25,female,Japanese idol,名詞,314,97,0.51,male,Japanese idol,0.26
16,番組,名詞,4926,1028,0.20,female,Japanese idol,名詞,382,87,0.45,male,Japanese idol,0.25
15,グループ,名詞,4960,1346,0.26,female,Japanese idol,名詞,227,98,0.51,male,Japanese idol,0.25
73,結成,名詞,1646,599,0.12,female,Japanese idol,名詞,119,70,0.36,male,Japanese idol,0.24
5,メンバー,名詞,9336,1920,0.38,female,Japanese idol,名詞,326,117,0.61,male,Japanese idol,0.23
3,出演,名詞,10362,1838,0.36,female,Japanese idol,名詞,506,109,0.57,male,Japanese idol,0.21
8,デビュー,名詞,6716,1594,0.31,female,Japanese idol,名詞,315,97,0.51,male,Japanese idol,0.20
62,学校,名詞,1926,668,0.13,female,Japanese idol,名詞,88,64,0.33,male,Japanese idol,0.20
7235,務める,動詞,3002,841,0.17,female,Japanese idol,動詞,145,69,0.36,male,Japanese idol,0.19
44,位,名詞,2560,491,0.10,female,Japanese idol,名詞,167,56,0.29,male,Japanese idol,0.19
32,テレビ,名詞,3178,861,0.17,female,Japanese idol,名詞,197,69,0.36,male,Japanese idol,0.19
94,高等,名詞,1356,532,0.10,female,Japanese idol,名詞,68,54,0.28,male,Japanese idol,0.18
78,主演,名詞,1628,404,0.08,female,Japanese idol,名詞,227,50,0.26,male,Japanese idol,0.18

## Prince and princess

In [97]:
# read overall file
princess = pd.read_csv("princess_text_overall.csv")

#total number of articles
princess_total_articles = len(glob.glob('../princess/new_csvs/*'))

# all nouns
princess_noun= princess[princess.pos =="名詞"].sort_values("total", ascending=False)
princess_noun["per_article"]= round(princess_noun["articles"]/ princess_total_articles,2)
princess_noun["gender"]= "female"
princess_noun["occupation"]= "prince and princess"
princess_noun.to_csv("princess_noun.csv", index= False)
# print_result = pd.read_csv("princess_noun.csv")

# top20 nouns
princess_top20_noun= princess_noun.head(20)
princess_top20_noun.to_csv("princess_top20_noun.csv", index= False)
# print_result = pd.read_csv("princess_top20_noun.csv")

# all verbs
princess_verb= princess[princess.pos =="動詞"].sort_values("total", ascending=False)
princess_verb["per_article"]= round(princess_verb["articles"]/ princess_total_articles,2)
princess_verb["gender"]= "female"
princess_verb["occupation"]= "prince and princess"
princess_verb.to_csv("princess_verb.csv", index= False)
# print_result = pd.read_csv("princess_verb.csv")

# top20 verbs
princess_top20_verb= princess_verb.head(20)
princess_top20_verb.to_csv("princess_top20_verb.csv", index= False)
# print_result = pd.read_csv("princess_top20_verb.csv")

# all adjs
princess_adj= princess[princess.pos =="形容詞"].sort_values("total", ascending=False)
princess_adj["per_article"]= round(princess_adj["articles"]/ princess_total_articles,2)
princess_adj["gender"]= "female"
princess_adj["occupation"]= "prince and princess"
princess_adj.to_csv("princess_adj.csv", index= False)
# print_result = pd.read_csv("princess_adj.csv")

# top20 adj
princess_top20_adj= princess_adj.head(20)
princess_top20_adj.to_csv("princess_top20_adj.csv", index= False)

In [98]:
# merge nouns + verbs + adjs
princess_top_words = pd.concat([princess_noun, princess_verb,princess_adj], axis=0)
princess_top_words.to_csv("princess_top_words.csv", index= False)
print_result = pd.read_csv("princess_top_words.csv")
print_result

        word  pos  total  articles  per_article  gender           occupation
0          世   名詞   2221       399         0.93  female  prince and princess
1         結婚   名詞   1017       401         0.94  female  prince and princess
2          王   名詞    986       322         0.75  female  prince and princess
3          公   名詞    985       292         0.68  female  prince and princess
4          夫   名詞    585       258         0.60  female  prince and princess
...      ...  ...    ...       ...          ...     ...                  ...
8193   むつまじい  形容詞      1         1         0.00  female  prince and princess
8194  みすぼらしい  形容詞      1         1         0.00  female  prince and princess
8195    まばゆい  形容詞      1         1         0.00  female  prince and princess
8196   ふさわしい  形容詞      1         1         0.00  female  prince and princess
8197     嬉しい  形容詞      1         1         0.00  female  prince and princess

[8198 rows x 7 columns]

In [100]:
# read overall file
prince = pd.read_csv("prince_text_overall.csv")

#total number of articles
prince_total_articles = len(glob.glob('../prince/new_csvs/*'))

# all nouns
prince_noun= prince[prince.pos =="名詞"].sort_values("total", ascending=False)
prince_noun["per_article"]= round(prince_noun["articles"]/ prince_total_articles,2)
prince_noun["gender"]= "male"
prince_noun["occupation"]= "prince and princess"
prince_noun.to_csv("prince_noun.csv", index= False)
# print_result = pd.read_csv("prince_noun.csv")

# top20 nouns
prince_top20_noun= prince_noun.head(20)
prince_top20_noun.to_csv("prince_top20_noun.csv", index= False)
# print_result = pd.read_csv("prince_top20_noun.csv")

# all verbs
prince_verb= prince[prince.pos =="動詞"].sort_values("total", ascending=False)
prince_verb["per_article"]= round(prince_verb["articles"]/ prince_total_articles,2)
prince_verb["gender"]= "male"
prince_verb["occupation"]= "prince and princess"
prince_verb.to_csv("prince_verb.csv", index= False)
# print_result = pd.read_csv("prince_verb.csv")

# top20 verbs
prince_top20_verb= prince_verb.head(20)
prince_top20_verb.to_csv("prince_top20_verb.csv", index= False)
# print_result = pd.read_csv("prince_top20_verb.csv")

# all adjs
prince_adj= prince[prince.pos =="形容詞"].sort_values("total", ascending=False)
prince_adj["per_article"]= round(prince_adj["articles"]/ prince_total_articles,2)
prince_adj["gender"]= "male"
prince_adj["occupation"]= "prince and princess"
prince_adj.to_csv("prince_adj.csv", index= False)
# print_result = pd.read_csv("prince_adj.csv")

# top20 adj
prince_top20_adj= prince_adj.head(20)
prince_top20_adj.to_csv("prince_top20_adj.csv", index= False)

In [101]:
# merge nouns + verbs + adjs
prince_top_words = pd.concat([prince_noun, prince_verb,prince_adj], axis=0)
prince_top_words.to_csv("prince_top_words.csv", index= False)
print_result = pd.read_csv("prince_top_words.csv")
print_result

       word  pos  total  articles  per_article gender           occupation
0         世   名詞   2470       305         0.92   male  prince and princess
1         公   名詞   1127       247         0.74   male  prince and princess
2         王   名詞    864       229         0.69   male  prince and princess
3      フランス   名詞    793       147         0.44   male  prince and princess
4         軍   名詞    762       127         0.38   male  prince and princess
...     ...  ...    ...       ...          ...    ...                  ...
8660  くだらない  形容詞      1         1         0.00   male  prince and princess
8661     くい  形容詞      1         1         0.00   male  prince and princess
8662    訝しい  形容詞      1         1         0.00   male  prince and princess
8663   許可ない  形容詞      1         1         0.00   male  prince and princess
8664    根深い  形容詞      1         1         0.00   male  prince and princess

[8665 rows x 7 columns]

In [102]:
# princess + prince
princessPrince_all_top_words = pd.concat([princess_top_words, prince_top_words], axis=0)
princessPrince_all_top_words.to_csv("princessPrince_all_top_words.csv", index= False)

In [149]:
princessPrince_all_top_words= pd.read_csv("princessPrince_all_top_words.csv")
princessPrince_all_top_words[princessPrince_all_top_words.word ==""]

     word pos  total  articles  per_article  gender           occupation
23     女王  名詞    273        89         0.21  female  prince and princess
8288   女王  名詞    110        49         0.15    male  prince and princess

In [130]:
princessPrince_all_top_words[princessPrince_all_top_words.gender == "female"]\
    .sort_values("per_article", ascending = False).head(60)

       word  pos  total  articles  per_article  gender           occupation
1        結婚   名詞   1017       401         0.94  female  prince and princess
0         世   名詞   2221       399         0.93  female  prince and princess
6694   生まれる   動詞    444       339         0.79  female  prince and princess
13       生涯   名詞    369       340         0.79  female  prince and princess
2         王   名詞    986       322         0.75  female  prince and princess
3         公   名詞    985       292         0.68  female  prince and princess
7         娘   名詞    448       272         0.64  female  prince and princess
5         妃   名詞    576       265         0.62  female  prince and princess
4         夫   名詞    585       258         0.60  female  prince and princess
11        女   名詞    380       228         0.53  female  prince and princess
18        妻   名詞    323       197         0.46  female  prince and princess
12       王妃   名詞    373       175         0.41  female  prince and princess
16      ドイツ   名詞    326       170         0.40  female  prince and princess
6695   もうける   動詞    179       167         0.39  female  prince and princess
17        母   名詞    325       166         0.39  female  prince and princess
31       子供   名詞    244       162         0.38  female  prince and princess
15        父   名詞    333       164         0.38  female  prince and princess
6        彼女   名詞    459       158         0.37  female  prince and princess
42       死去   名詞    207       154         0.36  female  prince and princess
37       王族   名詞    217       152         0.36  female  prince and princess
47       長女   名詞    184       150         0.35  female  prince and princess
10       王女   名詞    408       150         0.35  female  prince and princess
8        王子   名詞    418       148         0.35  female  prince and princess
41        妹   名詞    208       137         0.32  female  prince and princess
8033     ない  形容詞    264       131         0.31  female  prince and princess
27       息子   名詞    259       134         0.31  female  prince and princess
28       宮殿   名詞    258       133         0.31  female  prince and princess
14       大公   名詞    337       133         0.31  female  prince and princess
52        語   名詞    171       128         0.30  female  prince and princess
44        弟   名詞    203       129         0.30  female  prince and princess
9      イギリス   名詞    413       125         0.29  female  prince and princess
29       夫妻   名詞    251       125         0.29  female  prince and princess
22     フランス   名詞    277       120         0.28  female  prince and princess
20      カール   名詞    303       119         0.28  female  prince and princess
46        姉   名詞    191       116         0.27  female  prince and princess
64       最初   名詞    142       110         0.26  female  prince and princess
32       王位   名詞    242       112         0.26  female  prince and princess
6699   亡くなる   動詞    136       109         0.25  female  prince and princess
71       子女   名詞    137       109         0.25  female  prince and princess
26       継承   名詞    261       107         0.25  female  prince and princess
51        兄   名詞    171       109         0.25  female  prince and princess
33       太子   名詞    237       103         0.24  female  prince and princess
21       公爵   名詞    285       102         0.24  female  prince and princess
40       夫人   名詞    209        98         0.23  female  prince and princess
53        城   名詞    168       100         0.23  female  prince and princess
92        男   名詞    113       100         0.23  female  prince and princess
6696    受ける   動詞    178        99         0.23  female  prince and princess
56       生活   名詞    163        97         0.23  female  prince and princess
24       皇帝   名詞    272        99         0.23  female  prince and princess
50       宮廷   名詞    172        93         0.22  female  prince and princess
45       国王   名詞    195        93         0.22  female  prince and princess
74       長男   名詞    132        96         0.22  female  prince and princess
54        伯   名詞    166        93         0.22  female  prince and princess
79       のち   名詞    128        92         0.21  female  prince and princess
6700     呼ぶ   動詞    125        89         0.21  female  prince and princess
23       女王   名詞    273        89         0.21  female  prince and princess
96       次女   名詞    104        91         0.21  female  prince and princess
39        侯   名詞    212        89         0.21  female  prince and princess
25    デンマーク   名詞    271        84         0.20  female  prince and princess
63       誕生   名詞    150        84         0.20  female  prince and princess

In [201]:
# difference??
diff_princessprince = pd.merge(princess_top_words, prince_top_words, on="word")
diff_princessprince["diff_pct"] = abs(diff_princessprice.per_article_x - diff_princessprice.per_article_y)
diff_princessprince["diff_pct"].describe()

count    5056.000000
mean        0.012814
std         0.022121
min         0.000000
25%         0.000000
50%         0.010000
75%         0.010000
max         0.480000
Name: diff_pct, dtype: float64

In [202]:
diff_princessprince.sort_values("diff_pct", ascending = False).head(10)

,word,pos_x,total_x,articles_x,per_article_x,gender_x,occupation_x,pos_y,total_y,articles_y,per_article_y,gender_y,occupation_y,diff_pct
4,夫,名詞,585,258,0.60,female,prince and princess,名詞,56,41,0.12,male,prince and princess,0.48
172,軍,名詞,57,37,0.09,female,prince and princess,名詞,762,127,0.38,male,prince and princess,0.29
5,妃,名詞,576,265,0.62,female,prince and princess,名詞,160,124,0.37,male,prince and princess,0.25
126,戦争,名詞,79,46,0.11,female,prince and princess,名詞,355,114,0.34,male,prince and princess,0.23
47,長女,名詞,184,150,0.35,female,prince and princess,名詞,46,41,0.12,male,prince and princess,0.23
6,彼女,名詞,459,158,0.37,female,prince and princess,名詞,63,45,0.14,male,prince and princess,0.23
962,在位,名詞,10,8,0.02,female,prince and princess,名詞,115,79,0.24,male,prince and princess,0.22
12,王妃,名詞,373,175,0.41,female,prince and princess,名詞,112,62,0.19,male,prince and princess,0.22
609,軍人,名詞,16,15,0.04,female,prince and princess,名詞,119,83,0.25,male,prince and princess,0.21
709,官,名詞,14,13,0.03,female,prince and princess,名詞,155,75,0.23,male,prince and princess,0.20

## Figure Skater

In [151]:
# read overall file
femaleFigureSkater = pd.read_csv("femaleFigureSkater_text_overall.csv")

#total number of articles
femaleFigureSkater_total_articles = len(glob.glob('../femaleFigureSkater/new_csvs/*'))

# all nouns
femaleFigureSkater_noun= femaleFigureSkater[femaleFigureSkater.pos =="名詞"].sort_values("total", ascending=False)
femaleFigureSkater_noun["per_article"]= round(femaleFigureSkater_noun["articles"]/ femaleFigureSkater_total_articles,2)
femaleFigureSkater_noun["gender"]= "female"
femaleFigureSkater_noun["occupation"]= "figure skater"
femaleFigureSkater_noun.to_csv("femaleFigureSkater_noun.csv", index= False)
# print_result = pd.read_csv("femaleFigureSkater_noun.csv")

# top20 nouns
femaleFigureSkater_top20_noun= femaleFigureSkater_noun.head(20)
femaleFigureSkater_top20_noun.to_csv("femaleFigureSkater_top20_noun.csv", index= False)
# print_result = pd.read_csv("femaleFigureSkater_top20_noun.csv")

# all verbs
femaleFigureSkater_verb= femaleFigureSkater[femaleFigureSkater.pos =="動詞"].sort_values("total", ascending=False)
femaleFigureSkater_verb["per_article"]= round(femaleFigureSkater_verb["articles"]/ femaleFigureSkater_total_articles,2)
femaleFigureSkater_verb["gender"]= "female"
femaleFigureSkater_verb["occupation"]= "figure skater"
femaleFigureSkater_verb.to_csv("femaleFigureSkater_verb.csv", index= False)
# print_result = pd.read_csv("femaleFigureSkater_verb.csv")

# top20 verbs
femaleFigureSkater_top20_verb= femaleFigureSkater_verb.head(20)
femaleFigureSkater_top20_verb.to_csv("femaleFigureSkater_top20_verb.csv", index= False)
# print_result = pd.read_csv("femaleFigureSkater_top20_verb.csv")

# all adjs
femaleFigureSkater_adj= femaleFigureSkater[femaleFigureSkater.pos =="形容詞"].sort_values("total", ascending=False)
femaleFigureSkater_adj["per_article"]= round(femaleFigureSkater_adj["articles"]/ femaleFigureSkater_total_articles,2)
femaleFigureSkater_adj["gender"]= "female"
femaleFigureSkater_adj["occupation"]= "figure skater"
femaleFigureSkater_adj.to_csv("femaleFigureSkater_adj.csv", index= False)
# print_result = pd.read_csv("femaleFigureSkater_adj.csv")

# top20 adj
femaleFigureSkater_top20_adj= femaleFigureSkater_adj.head(20)
femaleFigureSkater_top20_adj.to_csv("femaleFigureSkater_top20_adj.csv", index= False)

In [152]:
# merge nouns + verbs + adjs
femaleFigureSkater_top_words = pd.concat([femaleFigureSkater_noun, femaleFigureSkater_verb,femaleFigureSkater_adj], axis=0)
femaleFigureSkater_top_words.to_csv("femaleFigureSkater_top_words.csv", index= False)
print_result = pd.read_csv("femaleFigureSkater_top_words.csv")
print_result

       word  pos  total  articles  per_article  gender     occupation
0       選手権   名詞   7549      1539         0.61  female  figure skater
1         位   名詞   7368      1050         0.42  female  figure skater
2      スケート   名詞   5824      2488         0.99  female  figure skater
3      シーズン   名詞   5005       903         0.36  female  figure skater
4     フィギュア   名詞   4248      2466         0.98  female  figure skater
...     ...  ...    ...       ...          ...     ...            ...
9377    つらい  形容詞      1         1         0.00  female  figure skater
9378  つまらない  形容詞      1         1         0.00  female  figure skater
9379    にぶい  形容詞      1         1         0.00  female  figure skater
9380     ぽい  形容詞      1         1         0.00  female  figure skater
9381   大人しい  形容詞      1         1         0.00  female  figure skater

[9382 rows x 7 columns]

In [155]:
# read overall file
maleFigureSkater = pd.read_csv("maleFigureSkater_text_overall.csv")

#total number of articles
maleFigureSkater_total_articles = len(glob.glob('../maleFigureSkater/new_csvs/*'))

# all nouns
maleFigureSkater_noun= maleFigureSkater[maleFigureSkater.pos =="名詞"].sort_values("total", ascending=False)
maleFigureSkater_noun["per_article"]= round(maleFigureSkater_noun["articles"]/ maleFigureSkater_total_articles,2)
maleFigureSkater_noun["gender"]= "male"
maleFigureSkater_noun["occupation"]= "figure skater"
maleFigureSkater_noun.to_csv("maleFigureSkater_noun.csv", index= False)
# print_result = pd.read_csv("maleFigureSkater_noun.csv")

# top20 nouns
maleFigureSkater_top20_noun= maleFigureSkater_noun.head(20)
maleFigureSkater_top20_noun.to_csv("maleFigureSkater_top20_noun.csv", index= False)
# print_result = pd.read_csv("maleFigureSkater_top20_noun.csv")

# all verbs
maleFigureSkater_verb= maleFigureSkater[maleFigureSkater.pos =="動詞"].sort_values("total", ascending=False)
maleFigureSkater_verb["per_article"]= round(maleFigureSkater_verb["articles"]/ maleFigureSkater_total_articles,2)
maleFigureSkater_verb["gender"]= "male"
maleFigureSkater_verb["occupation"]= "figure skater"
maleFigureSkater_verb.to_csv("maleFigureSkater_verb.csv", index= False)
# print_result = pd.read_csv("maleFigureSkater_verb.csv")

# top20 verbs
maleFigureSkater_top20_verb= maleFigureSkater_verb.head(20)
maleFigureSkater_top20_verb.to_csv("maleFigureSkater_top20_verb.csv", index= False)
# print_result = pd.read_csv("maleFigureSkater_top20_verb.csv")

# all adjs
maleFigureSkater_adj= maleFigureSkater[maleFigureSkater.pos =="形容詞"].sort_values("total", ascending=False)
maleFigureSkater_adj["per_article"]= round(maleFigureSkater_adj["articles"]/ maleFigureSkater_total_articles,2)
maleFigureSkater_adj["gender"]= "male"
maleFigureSkater_adj["occupation"]= "figure skater"
maleFigureSkater_adj.to_csv("maleFigureSkater_adj.csv", index= False)
# print_result = pd.read_csv("maleFigureSkater_adj.csv")

# top20 adj
maleFigureSkater_top20_adj= maleFigureSkater_adj.head(20)
maleFigureSkater_top20_adj.to_csv("maleFigureSkater_top20_adj.csv", index= False)

In [156]:
# merge nouns + verbs + adjs
maleFigureSkater_top_words = pd.concat([maleFigureSkater_noun, maleFigureSkater_verb,maleFigureSkater_adj], axis=0)
maleFigureSkater_top_words.to_csv("maleFigureSkater_top_words.csv", index= False)
print_result = pd.read_csv("maleFigureSkater_top_words.csv")
print_result

       word  pos  total  articles  per_article gender     occupation
0       選手権   名詞   2454       458         0.59   male  figure skater
1         位   名詞   2414       291         0.37   male  figure skater
2      スケート   名詞   2123       776         1.00   male  figure skater
3      シーズン   名詞   1515       222         0.29   male  figure skater
4     フィギュア   名詞   1485       775         1.00   male  figure skater
...     ...  ...    ...       ...          ...    ...            ...
6426    にくい  形容詞      1         1         0.00   male  figure skater
6427     すい  形容詞      1         1         0.00   male  figure skater
6428    すごい  形容詞      1         1         0.00   male  figure skater
6429    たかい  形容詞      1         1         0.00   male  figure skater
6430     固い  形容詞      1         1         0.00   male  figure skater

[6431 rows x 7 columns]

In [157]:
# f+m figure skaters
figureSkater_all_top_words = pd.concat([femaleFigureSkater_top_words, maleFigureSkater_top_words], axis=0)
figureSkater_all_top_words.to_csv("figureSkater_all_top_words.csv", index= False)

In [165]:
figureSkater_all_top_words= pd.read_csv("figureSkater_all_top_words.csv")
figureSkater_all_top_words[figureSkater_all_top_words.word== ""]

     word pos  total  articles  per_article  gender     occupation
8      優勝  名詞   3069      1038         0.41  female  figure skater
9391   優勝  名詞    943       311         0.40    male  figure skater

In [164]:
figureSkater_all_top_words[figureSkater_all_top_words.gender== "male"].sort_values("per_article", ascending =False).head(60)

          word pos  total  articles  per_article gender     occupation
9384      スケート  名詞   2123       776         1.00   male  figure skater
9386     フィギュア  名詞   1485       775         1.00   male  figure skater
9387        選手  名詞   1279       775         1.00   male  figure skater
9395        出身  名詞    716       677         0.87   male  figure skater
9392        男子  名詞    933       672         0.86   male  figure skater
9393      シングル  名詞    874       671         0.86   male  figure skater
9382       選手権  名詞   2454       458         0.59   male  figure skater
9398        代表  名詞    591       359         0.46   male  figure skater
9406        男性  名詞    337       330         0.42   male  figure skater
9391        優勝  名詞    943       311         0.40   male  figure skater
9394    オリンピック  名詞    841       299         0.38   male  figure skater
9383         位  名詞   2414       291         0.37   male  figure skater
9389        世界  名詞   1081       289         0.37   male  figure skater
9415        経歴  名詞    260       259         0.33   male  figure skater
9385      シーズン  名詞   1515       222         0.29   male  figure skater
9390        出場  名詞    999       226         0.29   male  figure skater
9396      ジュニア  名詞    694       210         0.27   male  figure skater
9397         杯  名詞    672       188         0.24   male  figure skater
9400        大会  名詞    539       176         0.23   male  figure skater
14786      始める  動詞    240       170         0.22   male  figure skater
9413        国際  名詞    296       161         0.21   male  figure skater
9401     グランプリ  名詞    538       155         0.20   male  figure skater
9416        引退  名詞    258       159         0.20   male  figure skater
9412        競技  名詞    297       145         0.19   male  figure skater
9403      シリーズ  名詞    405       141         0.18   male  figure skater
9424       シニア  名詞    226       135         0.17   male  figure skater
9438        現在  名詞    166       122         0.16   male  figure skater
9456   アメリカ合衆国  名詞    132       112         0.14   male  figure skater
9445     メダリスト  名詞    150       109         0.14   male  figure skater
14787      果たす  動詞    221       107         0.14   male  figure skater
9407       カナダ  名詞    329       110         0.14   male  figure skater
9468     パートナー  名詞    107        98         0.13   male  figure skater
9410       ロシア  名詞    314        99         0.13   male  figure skater
9402        獲得  名詞    447       103         0.13   male  figure skater
9448        参戦  名詞    141       100         0.13   male  figure skater
14795     生まれる  動詞    104       100         0.13   male  figure skater
9418        ペア  名詞    245       103         0.13   male  figure skater
9405        日本  名詞    350        99         0.13   male  figure skater
9425        大陸  名詞    217        91         0.12   male  figure skater
9428      アメリカ  名詞    205        97         0.12   male  figure skater
9437       クラス  名詞    166        95         0.12   male  figure skater
9388        回転  名詞   1124        93         0.12   male  figure skater
14788       入る  動詞    193        93         0.12   male  figure skater
9447       表彰台  名詞    142        82         0.11   male  figure skater
14789      終わる  動詞    172        86         0.11   male  figure skater
9399      ジャンプ  名詞    552        89         0.11   male  figure skater
9482         主  名詞     94        85         0.11   male  figure skater
9420        総合  名詞    231        74         0.10   male  figure skater
9440        連盟  名詞    165        74         0.10   male  figure skater
9419        練習  名詞    241        76         0.10   male  figure skater
9417     ファイナル  名詞    248        74         0.10   male  figure skater
9439        発表  名詞    165        76         0.10   male  figure skater
9432        欧州  名詞    185        77         0.10   male  figure skater
9434         初  名詞    175        75         0.10   male  figure skater
9469         州  名詞    104        73         0.09   male  figure skater
9476        成績  名詞     99        72         0.09   male  figure skater
9433        開催  名詞    178        72         0.09   male  figure skater
9512        人物  名詞     77        73         0.09   male  figure skater
9426        連続  名詞    212        72         0.09   male  figure skater
14791      受ける  動詞    166        73         0.09   male  figure skater

In [168]:
# difference??
diff_skater = pd.merge(femaleFigureSkater_top_words, maleFigureSkater_top_words, on="word")
diff_skater.head()

,word,pos_x,total_x,articles_x,per_article_x,gender_x,occupation_x,pos_y,total_y,articles_y,per_article_y,gender_y,occupation_y
0,選手権,名詞,7549,1539,0.61,female,figure skater,名詞,2454,458,0.59,male,figure skater
1,位,名詞,7368,1050,0.42,female,figure skater,名詞,2414,291,0.37,male,figure skater
2,スケート,名詞,5824,2488,0.99,female,figure skater,名詞,2123,776,1.00,male,figure skater
3,シーズン,名詞,5005,903,0.36,female,figure skater,名詞,1515,222,0.29,male,figure skater
4,フィギュア,名詞,4248,2466,0.98,female,figure skater,名詞,1485,775,1.00,male,figure skater

In [188]:
diff_skater["diff_pct"] = abs(diff_skater.per_article_x - diff_skater.per_article_y)

In [193]:
diff_skater["diff_pct"].describe()

count    4569.000000
mean        0.003631
std         0.017462
min         0.000000
25%         0.000000
50%         0.000000
75%         0.010000
max         0.760000
Name: diff_pct, dtype: float64

In [199]:
diff_skater.sort_values("diff_pct", ascending = False).head(10)

,word,pos_x,total_x,articles_x,per_article_x,gender_x,occupation_x,pos_y,total_y,articles_y,per_article_y,gender_y,occupation_y,diff_pct
83,男子,名詞,307,251,0.10,female,figure skater,名詞,933,672,0.86,male,figure skater,0.76
15,女子,名詞,1753,1275,0.50,female,figure skater,名詞,23,19,0.02,male,figure skater,0.48
24,女性,名詞,1029,994,0.39,female,figure skater,名詞,21,14,0.02,male,figure skater,0.37
19,パートナー,名詞,1350,1144,0.45,female,figure skater,名詞,107,98,0.13,male,figure skater,0.32
13,シングル,名詞,1901,1503,0.60,female,figure skater,名詞,874,671,0.86,male,figure skater,0.26
47,男性,名詞,542,542,0.21,female,figure skater,名詞,337,330,0.42,male,figure skater,0.21
28,アイスダンス,名詞,922,618,0.24,female,figure skater,名詞,60,45,0.06,male,figure skater,0.18
33,結成,名詞,782,447,0.18,female,figure skater,名詞,46,28,0.04,male,figure skater,0.14
32,カップル,名詞,808,301,0.12,female,figure skater,名詞,27,15,0.02,male,figure skater,0.10
68,解散,名詞,369,254,0.10,female,figure skater,名詞,14,10,0.01,male,figure skater,0.09